In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9648, 1392, 6051, 115],
 [9648, 1392, 6051, 2856],
 [9648, 8801, 6051, 5556],
 [6876, 753, 7743, 1932, 4207],
 [6876, 753, 7743, 1932, 1725],
 [8664, 9648, 1331, 6051, 153],
 [4417, 840, 2500, 1932]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9648 1392 6051  115]
 [   0    0    0    0 9648 1392 6051 2856]
 [   0    0    0    0 9648 8801 6051 5556]
 [   0    0    0 6876  753 7743 1932 4207]
 [   0    0    0 6876  753 7743 1932 1725]
 [   0    0    0 8664 9648 1331 6051  153]
 [   0    0    0    0 4417  840 2500 1932]]


In [9]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 58ms/step


array([[[ 1.2340676e-02, -3.9141346e-02, -3.2665506e-03,  4.1023348e-02,
         -4.3589890e-02, -1.4905296e-02,  1.4331821e-02, -1.9481277e-02,
         -3.9281894e-02,  1.0762669e-02],
        [ 1.2340676e-02, -3.9141346e-02, -3.2665506e-03,  4.1023348e-02,
         -4.3589890e-02, -1.4905296e-02,  1.4331821e-02, -1.9481277e-02,
         -3.9281894e-02,  1.0762669e-02],
        [ 1.2340676e-02, -3.9141346e-02, -3.2665506e-03,  4.1023348e-02,
         -4.3589890e-02, -1.4905296e-02,  1.4331821e-02, -1.9481277e-02,
         -3.9281894e-02,  1.0762669e-02],
        [ 1.2340676e-02, -3.9141346e-02, -3.2665506e-03,  4.1023348e-02,
         -4.3589890e-02, -1.4905296e-02,  1.4331821e-02, -1.9481277e-02,
         -3.9281894e-02,  1.0762669e-02],
        [-1.9312084e-02,  3.0652586e-02,  4.0977169e-02,  3.1123865e-02,
         -4.5361187e-02, -6.8307146e-03, -1.4053442e-02,  4.3894935e-02,
         -3.6409307e-02, -2.9054988e-02],
        [-4.6871223e-02,  4.3131795e-02, -8.6168163e-03,  3.

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9648, 1392, 6051,  115])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 28ms/step


array([[ 0.01234068, -0.03914135, -0.00326655,  0.04102335, -0.04358989,
        -0.0149053 ,  0.01433182, -0.01948128, -0.03928189,  0.01076267],
       [ 0.01234068, -0.03914135, -0.00326655,  0.04102335, -0.04358989,
        -0.0149053 ,  0.01433182, -0.01948128, -0.03928189,  0.01076267],
       [ 0.01234068, -0.03914135, -0.00326655,  0.04102335, -0.04358989,
        -0.0149053 ,  0.01433182, -0.01948128, -0.03928189,  0.01076267],
       [ 0.01234068, -0.03914135, -0.00326655,  0.04102335, -0.04358989,
        -0.0149053 ,  0.01433182, -0.01948128, -0.03928189,  0.01076267],
       [-0.01931208,  0.03065259,  0.04097717,  0.03112387, -0.04536119,
        -0.00683071, -0.01405344,  0.04389494, -0.03640931, -0.02905499],
       [-0.04687122,  0.04313179, -0.00861682,  0.03322521,  0.0496346 ,
        -0.03059697, -0.02187301,  0.01093309,  0.01939404, -0.04455758],
       [-0.04807198, -0.04845259,  0.00397591,  0.00362648, -0.02333344,
        -0.04565495, -0.02301996, -0.02851763